# install lemp on target server in optimized format
---
- name: install LEMP stack on target server
  hosts: targetservers
  become: yes #to assign sudo privileges
  tasks:
    - name: install nginx, mariadb105-server, php, php-fpm
      ansible.builtin.dnf:
        name:
          - nginx
          - mariadb105-server
          - php
          - php-fpm
        state: present
    - name: start and enable nginx mariadb php-fpm service
      ansible.builtin.systemd_service:
        name: "{{item}}"
        state: started
        enabled: true
      loop:
        - nginx
        - mariadb
        - php-fpm    
    - name: deploy index.php file
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.php
        content: "<?php phpinfo(); ?>"