---
- name: Install nginx on server with handler
  hosts: targetserver
  become: yes

  vars:
    web_packages: nginx      
    web_service: nginx
    web_root: /usr/share/nginx/html
    con_file: /etc/nginx/conf.d/custom.conf

  tasks:
    - name: Install nginx package
      ansible.builtin.dnf:
        name: "{{ web_packages }}"
        state: present

    - name: Start and enable nginx service
      ansible.builtin.systemd_service:
        name: "{{ web_service }}"
        state: started
        enabled: true

    - name: Configure nginx
      ansible.builtin.blockinfile:
        path: "{{ con_file }}"
        create: yes
        block: |
          server {
              listen 80;         
              root /usr/share/nginx/html;
              index index.html index.htm;
          }
      notify: Restart nginx

    - name: Deploy index.html
      ansible.builtin.copy:
        dest: "{{ web_root }}/index.html"
        content: |
          <html>
          <head><title>Welcome</title></head>
          <body><h1>Hello from Ansible with handler!</h1></body>
          </html>
  handlers:
    - name: Restart nginx
      ansible.builtin._systemd_service:
        name: "{{ web_service }}"
        state: restarted